---
- include_tasks: vscode.yml
- include_tasks: cli-tools.yml
- include_tasks: git.yml
- include_tasks: sublime.yml
- include_tasks: dev-frameworks.yml
- include_tasks: lazy-git.yml
- include_tasks: dbeaver.yml
- include_tasks: jira-cli.yml
